// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CastleModel
    {
        /// <summary>
        /// Initializes a new instance of the CastleModel class.
        /// </summary>
        public CastleModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CastleModel class.
        /// </summary>
        public CastleModel(LocationModel position = default(LocationModel))
        {
            Position = position;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Position")]
        public LocationModel Position { get; set; }

    }
}
