// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient
{
    using System.Threading;
    using System.Threading.Tasks;

    /// <summary>
    /// Extension methods for Castles.
    /// </summary>
    public static partial class CastlesExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            public static object GetCastles(this ICastles operations)
            {
                return operations.GetCastlesAsync().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<object> GetCastlesAsync(this ICastles operations, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetCastlesWithHttpMessagesAsync(null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
