// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BattalionModel
    {
        /// <summary>
        /// Initializes a new instance of the BattalionModel class.
        /// </summary>
        public BattalionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattalionModel class.
        /// </summary>
        public BattalionModel(string castleId = default(string), string destinationCastleId = default(string), IList<string> soldiers = default(IList<string>), System.Guid? id = default(System.Guid?), int? percentOfSelectedSoldiers = default(int?), bool? moveByPercent = default(bool?))
        {
            CastleId = castleId;
            DestinationCastleId = destinationCastleId;
            Soldiers = soldiers;
            Id = id;
            PercentOfSelectedSoldiers = percentOfSelectedSoldiers;
            MoveByPercent = moveByPercent;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "castleId")]
        public string CastleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destinationCastleId")]
        public string DestinationCastleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "soldiers")]
        public IList<string> Soldiers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "percentOfSelectedSoldiers")]
        public int? PercentOfSelectedSoldiers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "moveByPercent")]
        public bool? MoveByPercent { get; set; }

    }
}
