// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class BattalionMovementEventModel
    {
        /// <summary>
        /// Initializes a new instance of the BattalionMovementEventModel
        /// class.
        /// </summary>
        public BattalionMovementEventModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the BattalionMovementEventModel
        /// class.
        /// </summary>
        public BattalionMovementEventModel(System.Guid? castleId = default(System.Guid?), System.Guid? destinationCastleId = default(System.Guid?), IList<string> soldiers = default(IList<string>), RouteModel route = default(RouteModel), System.Guid? id = default(System.Guid?), System.DateTime? runningAt = default(System.DateTime?), System.DateTime? executeAt = default(System.DateTime?), string type = default(string))
        {
            CastleId = castleId;
            DestinationCastleId = destinationCastleId;
            Soldiers = soldiers;
            Route = route;
            Id = id;
            RunningAt = runningAt;
            ExecuteAt = executeAt;
            Type = type;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "castleId")]
        public System.Guid? CastleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "destinationCastleId")]
        public System.Guid? DestinationCastleId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "soldiers")]
        public IList<string> Soldiers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "route")]
        public RouteModel Route { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "runningAt")]
        public System.DateTime? RunningAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "executeAt")]
        public System.DateTime? ExecuteAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; private set; }

    }
}
