// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CastleStateModel
    {
        /// <summary>
        /// Initializes a new instance of the CastleStateModel class.
        /// </summary>
        public CastleStateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CastleStateModel class.
        /// </summary>
        /// <param name="army">Possible values include: 'Neutrual', 'Red',
        /// 'Blue'</param>
        public CastleStateModel(string id = default(string), string name = default(string), int? soldiersAmount = default(int?), CastleTroopTypeModel castleTroopType = default(CastleTroopTypeModel), System.DateTime? produceExecuteAt = default(System.DateTime?), PositionModel position = default(PositionModel), string army = default(string), string ownerUserId = default(string), string ownerId = default(string), SiegeStateModel siege = default(SiegeStateModel))
        {
            Id = id;
            Name = name;
            SoldiersAmount = soldiersAmount;
            CastleTroopType = castleTroopType;
            ProduceExecuteAt = produceExecuteAt;
            Position = position;
            Army = army;
            OwnerUserId = ownerUserId;
            OwnerId = ownerId;
            Siege = siege;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "soldiersAmount")]
        public int? SoldiersAmount { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "castleTroopType")]
        public CastleTroopTypeModel CastleTroopType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "produceExecuteAt")]
        public System.DateTime? ProduceExecuteAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "position")]
        public PositionModel Position { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Neutrual', 'Red', 'Blue'
        /// </summary>
        [JsonProperty(PropertyName = "army")]
        public string Army { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerUserId")]
        public string OwnerUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerId")]
        public string OwnerId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siege")]
        public SiegeStateModel Siege { get; set; }

    }
}
