// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class CastleRouteStateModel
    {
        /// <summary>
        /// Initializes a new instance of the CastleRouteStateModel class.
        /// </summary>
        public CastleRouteStateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CastleRouteStateModel class.
        /// </summary>
        public CastleRouteStateModel(string fromCastle = default(string), string toCastle = default(string), RouteModel route = default(RouteModel))
        {
            FromCastle = fromCastle;
            ToCastle = toCastle;
            Route = route;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fromCastle")]
        public string FromCastle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "toCastle")]
        public string ToCastle { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "route")]
        public RouteModel Route { get; set; }

    }
}
