// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class ChangeTroopTypeModel
    {
        /// <summary>
        /// Initializes a new instance of the ChangeTroopTypeModel class.
        /// </summary>
        public ChangeTroopTypeModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the ChangeTroopTypeModel class.
        /// </summary>
        public ChangeTroopTypeModel(string type = default(string), string castleId = default(string))
        {
            Type = type;
            CastleId = castleId;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "type")]
        public string Type { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "castleId")]
        public string CastleId { get; set; }

    }
}
