// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GameAcceptedModel
    {
        /// <summary>
        /// Initializes a new instance of the GameAcceptedModel class.
        /// </summary>
        public GameAcceptedModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GameAcceptedModel class.
        /// </summary>
        public GameAcceptedModel(GameArmySettingModel armySetting = default(GameArmySettingModel))
        {
            ArmySetting = armySetting;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "armySetting")]
        public GameArmySettingModel ArmySetting { get; set; }

    }
}
