// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class GetCastlesResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetCastlesResponse class.
        /// </summary>
        public GetCastlesResponse()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GetCastlesResponse class.
        /// </summary>
        public GetCastlesResponse(IList<CastleModel> castles = default(IList<CastleModel>), IList<RouteModel> routes = default(IList<RouteModel>))
        {
            Castles = castles;
            Routes = routes;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Castles")]
        public IList<CastleModel> Castles { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Routes")]
        public IList<RouteModel> Routes { get; set; }

    }
}
