// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class HeroStateModel
    {
        /// <summary>
        /// Initializes a new instance of the HeroStateModel class.
        /// </summary>
        public HeroStateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the HeroStateModel class.
        /// </summary>
        /// <param name="army">Possible values include: 'Neutrual', 'Red',
        /// 'Blue'</param>
        public HeroStateModel(string id = default(string), string userId = default(string), string army = default(string), System.DateTime? updatedAt = default(System.DateTime?))
        {
            Id = id;
            UserId = userId;
            Army = army;
            UpdatedAt = updatedAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "userId")]
        public string UserId { get; set; }

        /// <summary>
        /// Gets or sets possible values include: 'Neutrual', 'Red', 'Blue'
        /// </summary>
        [JsonProperty(PropertyName = "army")]
        public string Army { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

    }
}
