// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LocationModel
    {
        /// <summary>
        /// Initializes a new instance of the LocationModel class.
        /// </summary>
        public LocationModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LocationModel class.
        /// </summary>
        public LocationModel(double? lat = default(double?), double? lng = default(double?))
        {
            Lat = lat;
            Lng = lng;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lat")]
        public double? Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Lng")]
        public double? Lng { get; set; }

    }
}
