// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class LoginsDto
    {
        /// <summary>
        /// Initializes a new instance of the LoginsDto class.
        /// </summary>
        public LoginsDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the LoginsDto class.
        /// </summary>
        public LoginsDto(string loginProvider = default(string), string providerKey = default(string))
        {
            LoginProvider = loginProvider;
            ProviderKey = providerKey;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "loginProvider")]
        public string LoginProvider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "providerKey")]
        public string ProviderKey { get; set; }

    }
}
