// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class OpponentExtInfoModel
    {
        /// <summary>
        /// Initializes a new instance of the OpponentExtInfoModel class.
        /// </summary>
        public OpponentExtInfoModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the OpponentExtInfoModel class.
        /// </summary>
        public OpponentExtInfoModel(string provider = default(string), string key = default(string), string keyName = default(string))
        {
            Provider = provider;
            Key = key;
            KeyName = keyName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "provider")]
        public string Provider { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "key")]
        public string Key { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "keyName")]
        public string KeyName { get; set; }

    }
}
