// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PositionModel
    {
        /// <summary>
        /// Initializes a new instance of the PositionModel class.
        /// </summary>
        public PositionModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PositionModel class.
        /// </summary>
        public PositionModel(double? lat = default(double?), double? lng = default(double?), string address = default(string), System.DateTime? updatedAt = default(System.DateTime?))
        {
            Lat = lat;
            Lng = lng;
            Address = address;
            UpdatedAt = updatedAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lat")]
        public double? Lat { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "lng")]
        public double? Lng { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "updatedAt")]
        public System.DateTime? UpdatedAt { get; set; }

    }
}
