// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class RouteModel
    {
        /// <summary>
        /// Initializes a new instance of the RouteModel class.
        /// </summary>
        public RouteModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RouteModel class.
        /// </summary>
        public RouteModel(IList<RouteStepModel> steps = default(IList<RouteStepModel>), string duration = default(string), double? distance = default(double?))
        {
            Steps = steps;
            Duration = duration;
            Distance = distance;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "steps")]
        public IList<RouteStepModel> Steps { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "duration")]
        public string Duration { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "distance")]
        public double? Distance { get; set; }

    }
}
