// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class SiegeStateModel
    {
        /// <summary>
        /// Initializes a new instance of the SiegeStateModel class.
        /// </summary>
        public SiegeStateModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SiegeStateModel class.
        /// </summary>
        public SiegeStateModel(System.Guid? id = default(System.Guid?), string ownerUserId = default(string), UserModel ownerUser = default(UserModel), System.DateTime? battleAt = default(System.DateTime?), IList<SoldierModel> soldiers = default(IList<SoldierModel>), System.DateTime? siegeAt = default(System.DateTime?))
        {
            Id = id;
            OwnerUserId = ownerUserId;
            OwnerUser = ownerUser;
            BattleAt = battleAt;
            Soldiers = soldiers;
            SiegeAt = siegeAt;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public System.Guid? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerUserId")]
        public string OwnerUserId { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "ownerUser")]
        public UserModel OwnerUser { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "battleAt")]
        public System.DateTime? BattleAt { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "soldiers")]
        public IList<SoldierModel> Soldiers { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "siegeAt")]
        public System.DateTime? SiegeAt { get; set; }

    }
}
