// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Linq;

    public partial class SoldierModel
    {
        /// <summary>
        /// Initializes a new instance of the SoldierModel class.
        /// </summary>
        public SoldierModel()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the SoldierModel class.
        /// </summary>
        public SoldierModel(CastleTroopTypeModel castleTroopType = default(CastleTroopTypeModel), double? upkeepCoins = default(double?), string id = default(string))
        {
            CastleTroopType = castleTroopType;
            UpkeepCoins = upkeepCoins;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "castleTroopType")]
        public CastleTroopTypeModel CastleTroopType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "upkeepCoins")]
        public double? UpkeepCoins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
