// <auto-generated>
// Code generated by Microsoft (R) AutoRest Code Generator.
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.
// </auto-generated>

namespace VirtualRisks.WebApi.RestClient.Models
{
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class UserDto
    {
        /// <summary>
        /// Initializes a new instance of the UserDto class.
        /// </summary>
        public UserDto()
        {
            CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the UserDto class.
        /// </summary>
        public UserDto(string name = default(string), string email = default(string), bool? isActive = default(bool?), IList<LoginsDto> logins = default(IList<LoginsDto>), bool? isAdmin = default(bool?), string avatar = default(string), IList<HeroModel> heroes = default(IList<HeroModel>), IList<NotifyTokenDto> tokens = default(IList<NotifyTokenDto>), string id = default(string))
        {
            Name = name;
            Email = email;
            IsActive = isActive;
            Logins = logins;
            IsAdmin = isAdmin;
            Avatar = avatar;
            Heroes = heroes;
            Tokens = tokens;
            Id = id;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "email")]
        public string Email { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isActive")]
        public bool? IsActive { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "logins")]
        public IList<LoginsDto> Logins { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isAdmin")]
        public bool? IsAdmin { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "avatar")]
        public string Avatar { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "heroes")]
        public IList<HeroModel> Heroes { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tokens")]
        public IList<NotifyTokenDto> Tokens { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public string Id { get; set; }

    }
}
