//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VirtualRisks.Mobiles.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VirtualRisks.Mobiles.Resources.AppResource", typeof(AppResource).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already accepted this game.
        /// </summary>
        internal static string alert_alreadyaccepted {
            get {
                return ResourceManager.GetString("alert_alreadyaccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game difficulty.
        /// </summary>
        internal static string alert_gamedifficulty {
            get {
                return ResourceManager.GetString("alert_gamedifficulty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game ended!.
        /// </summary>
        internal static string alert_gameended {
            get {
                return ResourceManager.GetString("alert_gameended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game removed successfully.
        /// </summary>
        internal static string alert_gameremoved {
            get {
                return ResourceManager.GetString("alert_gameremoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select game speed.
        /// </summary>
        internal static string alert_gamespeed_title {
            get {
                return ResourceManager.GetString("alert_gamespeed_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your session was ended! Please login again to use app.
        /// </summary>
        internal static string alert_sessionended {
            get {
                return ResourceManager.GetString("alert_sessionended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;&lt; Back.
        /// </summary>
        internal static string bt_back {
            get {
                return ResourceManager.GetString("bt_back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Challenge &gt;&gt;.
        /// </summary>
        internal static string bt_challenge {
            get {
                return ResourceManager.GetString("bt_challenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLOSE.
        /// </summary>
        internal static string bt_close {
            get {
                return ResourceManager.GetString("bt_close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Game.
        /// </summary>
        internal static string bt_creategame {
            get {
                return ResourceManager.GetString("bt_creategame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MOVE.
        /// </summary>
        internal static string bt_move {
            get {
                return ResourceManager.GetString("bt_move", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ORDER.
        /// </summary>
        internal static string bt_order {
            get {
                return ResourceManager.GetString("bt_order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGRET.
        /// </summary>
        internal static string bt_regret {
            get {
                return ResourceManager.GetString("bt_regret", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change production troop type?.
        /// </summary>
        internal static string changeproductiontrooptype {
            get {
                return ResourceManager.GetString("changeproductiontrooptype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Computer.
        /// </summary>
        internal static string computer {
            get {
                return ResourceManager.GetString("computer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to move the soldiers from castle {0} to {1}.
        /// </summary>
        internal static string confirm_battalion_message {
            get {
                return ResourceManager.GetString("confirm_battalion_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept.
        /// </summary>
        internal static string confirm_bt_accept {
            get {
                return ResourceManager.GetString("confirm_bt_accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        internal static string confirm_bt_reject {
            get {
                return ResourceManager.GetString("confirm_bt_reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with computer.
        /// </summary>
        internal static string confirm_option_creategame_withcomputer {
            get {
                return ResourceManager.GetString("confirm_option_creategame_withcomputer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play with my friend.
        /// </summary>
        internal static string confirm_option_creategame_withfriend {
            get {
                return ResourceManager.GetString("confirm_option_creategame_withfriend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to play game now?.
        /// </summary>
        internal static string confirm_playgame_message {
            get {
                return ResourceManager.GetString("confirm_playgame_message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to remove this game?.
        /// </summary>
        internal static string confirm_removegame {
            get {
                return ResourceManager.GetString("confirm_removegame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string confirm_title {
            get {
                return ResourceManager.GetString("confirm_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who will be your opponent?.
        /// </summary>
        internal static string confirm_title_creategame {
            get {
                return ResourceManager.GetString("confirm_title_creategame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game invitation.
        /// </summary>
        internal static string confirm_title_gameinvite {
            get {
                return ResourceManager.GetString("confirm_title_gameinvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your army.
        /// </summary>
        internal static string confirm_title_selectarmy {
            get {
                return ResourceManager.GetString("confirm_title_selectarmy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose at least one Facebook friend to challenge.
        /// </summary>
        internal static string creategame_header {
            get {
                return ResourceManager.GetString("creategame_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battalion error!.
        /// </summary>
        internal static string error_battalion {
            get {
                return ResourceManager.GetString("error_battalion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game not found.
        /// </summary>
        internal static string error_game_notfound {
            get {
                return ResourceManager.GetString("error_game_notfound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when get game state.
        /// </summary>
        internal static string error_gamestate {
            get {
                return ResourceManager.GetString("error_gamestate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get your location.
        /// </summary>
        internal static string error_getlocation {
            get {
                return ResourceManager.GetString("error_getlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when init game....
        /// </summary>
        internal static string error_init_game {
            get {
                return ResourceManager.GetString("error_init_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has add more soldiers to {1}.
        /// </summary>
        internal static string event_addmoresoldiertocastle {
            get {
                return ResourceManager.GetString("event_addmoresoldiertocastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has add more soldiers to siege at {1}.
        /// </summary>
        internal static string event_addmoresoldiertosiege {
            get {
                return ResourceManager.GetString("event_addmoresoldiertosiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battle for {0} has begun.
        /// </summary>
        internal static string event_battlebegun {
            get {
                return ResourceManager.GetString("event_battlebegun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The battle for {0}&apos;s siege has begun.
        /// </summary>
        internal static string event_battlevssiege {
            get {
                return ResourceManager.GetString("event_battlevssiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost Castle {0} to the Enemy.
        /// </summary>
        internal static string event_castlehasbeenoccupied {
            get {
                return ResourceManager.GetString("event_castlehasbeenoccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You defended the attack from the Enemy.
        /// </summary>
        internal static string event_defendedcastle {
            get {
                return ResourceManager.GetString("event_defendedcastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your siege at {0} defended the attack from the enemy&apos;s siege.
        /// </summary>
        internal static string event_defendedsiege {
            get {
                return ResourceManager.GetString("event_defendedsiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lose when attacked {0}.
        /// </summary>
        internal static string event_failedattackcastle {
            get {
                return ResourceManager.GetString("event_failedattackcastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your siege lose when attack the enemy&apos;s siege at {0}.
        /// </summary>
        internal static string event_failedattacksiege {
            get {
                return ResourceManager.GetString("event_failedattacksiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You occupied the {0}.
        /// </summary>
        internal static string event_occupiedcastle {
            get {
                return ResourceManager.GetString("event_occupiedcastle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You occupied siege slot at {0}.
        /// </summary>
        internal static string event_occupiedsiege {
            get {
                return ResourceManager.GetString("event_occupiedsiege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You lost siege at {0} to the enemy.
        /// </summary>
        internal static string event_siegehasbeenoccupied {
            get {
                return ResourceManager.GetString("event_siegehasbeenoccupied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} has setup siege at {1}.
        /// </summary>
        internal static string event_siegehassetup {
            get {
                return ResourceManager.GetString("event_siegehassetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast.
        /// </summary>
        internal static string gamespeed_fast {
            get {
                return ResourceManager.GetString("gamespeed_fast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string gamespeed_low {
            get {
                return ResourceManager.GetString("gamespeed_low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string gamespeed_normal {
            get {
                return ResourceManager.GetString("gamespeed_normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speedy.
        /// </summary>
        internal static string gamespeed_speedy {
            get {
                return ResourceManager.GetString("gamespeed_speedy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra fast.
        /// </summary>
        internal static string gamespeed_ultrafast {
            get {
                return ResourceManager.GetString("gamespeed_ultrafast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ultra slow.
        /// </summary>
        internal static string gamespeed_ultraslow {
            get {
                return ResourceManager.GetString("gamespeed_ultraslow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defenders.
        /// </summary>
        internal static string header_defenders {
            get {
                return ResourceManager.GetString("header_defenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        internal static string header_production {
            get {
                return ResourceManager.GetString("header_production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance: {0} - Your soldiers will siege at castle in {1}.
        /// </summary>
        internal static string label_battalionrouteinfo {
            get {
                return ResourceManager.GetString("label_battalionrouteinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battle in {0}:{1}.
        /// </summary>
        internal static string lb_battletime {
            get {
                return ResourceManager.GetString("lb_battletime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neutral castle has init.
        /// </summary>
        internal static string lb_castleinit_neutral {
            get {
                return ResourceManager.GetString("lb_castleinit_neutral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent castle has init.
        /// </summary>
        internal static string lb_castleinit_opponent {
            get {
                return ResourceManager.GetString("lb_castleinit_opponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your castle has init.
        /// </summary>
        internal static string lb_castleinit_user {
            get {
                return ResourceManager.GetString("lb_castleinit_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose login method.
        /// </summary>
        internal static string lb_chooselogin {
            get {
                return ResourceManager.GetString("lb_chooselogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rangstrup IT.
        /// </summary>
        internal static string lb_copyright {
            get {
                return ResourceManager.GetString("lb_copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Castle is full. Order soldiers to move to continue production.
        /// </summary>
        internal static string lb_fullsoldier {
            get {
                return ResourceManager.GetString("lb_fullsoldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the castle where you want to send the selected 1 soldier.
        /// </summary>
        internal static string lb_movesoldier {
            get {
                return ResourceManager.GetString("lb_movesoldier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the castle where you want to send the selected {0} soldiers.
        /// </summary>
        internal static string lb_movesoldiers {
            get {
                return ResourceManager.GetString("lb_movesoldiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is winner!.
        /// </summary>
        internal static string lb_opponentwin {
            get {
                return ResourceManager.GetString("lb_opponentwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Owned by.
        /// </summary>
        internal static string lb_ownedby {
            get {
                return ResourceManager.GetString("lb_ownedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Produce {0} completed in {1}:{2}.
        /// </summary>
        internal static string lb_producetime {
            get {
                return ResourceManager.GetString("lb_producetime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Suspended.
        /// </summary>
        internal static string lb_productionsuspended {
            get {
                return ResourceManager.GetString("lb_productionsuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege.
        /// </summary>
        internal static string lb_siege {
            get {
                return ResourceManager.GetString("lb_siege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sieges.
        /// </summary>
        internal static string lb_sieges {
            get {
                return ResourceManager.GetString("lb_sieges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You win!.
        /// </summary>
        internal static string lb_youwin {
            get {
                return ResourceManager.GetString("lb_youwin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading {
            get {
                return ResourceManager.GetString("loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepting....
        /// </summary>
        internal static string loading_accepting {
            get {
                return ResourceManager.GetString("loading_accepting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting battalion.....
        /// </summary>
        internal static string loading_battalion {
            get {
                return ResourceManager.GetString("loading_battalion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating.....
        /// </summary>
        internal static string loading_create {
            get {
                return ResourceManager.GetString("loading_create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get game info....
        /// </summary>
        internal static string loading_game {
            get {
                return ResourceManager.GetString("loading_game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting your location.....
        /// </summary>
        internal static string loading_getlocation {
            get {
                return ResourceManager.GetString("loading_getlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initing....
        /// </summary>
        internal static string loading_init {
            get {
                return ResourceManager.GetString("loading_init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for a friend to create a game, create your own game or continue an existing game.
        /// </summary>
        internal static string main_header {
            get {
                return ResourceManager.GetString("main_header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not been invited to join any games and have not created any games either.
        /// </summary>
        internal static string main_nogame {
            get {
                return ResourceManager.GetString("main_nogame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Hero.
        /// </summary>
        internal static string myhero {
            get {
                return ResourceManager.GetString("myhero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production was paused because army not enough coins..
        /// </summary>
        internal static string notenoughcoinforproduction {
            get {
                return ResourceManager.GetString("notenoughcoinforproduction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent&apos;s hero.
        /// </summary>
        internal static string opponent_hero {
            get {
                return ResourceManager.GetString("opponent_hero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opponent&apos;s hero - {0}.
        /// </summary>
        internal static string opponent_hero_with_time {
            get {
                return ResourceManager.GetString("opponent_hero_with_time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string remove {
            get {
                return ResourceManager.GetString("remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing....
        /// </summary>
        internal static string removing {
            get {
                return ResourceManager.GetString("removing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string revenue {
            get {
                return ResourceManager.GetString("revenue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string score {
            get {
                return ResourceManager.GetString("score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string selectall {
            get {
                return ResourceManager.GetString("selectall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get latest state....
        /// </summary>
        internal static string status_buildgame {
            get {
                return ResourceManager.GetString("status_buildgame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game accepted successfully!.
        /// </summary>
        internal static string success_acceptgame_title {
            get {
                return ResourceManager.GetString("success_acceptgame_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Battalion successfully!.
        /// </summary>
        internal static string success_battalion {
            get {
                return ResourceManager.GetString("success_battalion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game successfully!.
        /// </summary>
        internal static string success_creategame {
            get {
                return ResourceManager.GetString("success_creategame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create game successfully, Please waiting for accept from your opponent..
        /// </summary>
        internal static string success_creategameandwait {
            get {
                return ResourceManager.GetString("success_creategameandwait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vs..
        /// </summary>
        internal static string vs {
            get {
                return ResourceManager.GetString("vs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You.
        /// </summary>
        internal static string you {
            get {
                return ResourceManager.GetString("you", resourceCulture);
            }
        }
    }
}
